"""
Schema helper for the mintmory://schema MCP resource (MM-40).

Provides a curated one-line description per MemoryCategory / ConceptLinkType /
MemorySource value. Names are always iterated from the live enums; descriptions
are kept in the CATEGORY_DESCRIPTIONS / LINK_TYPE_DESCRIPTIONS / SOURCE_DESCRIPTIONS
maps below. A coverage guard raises KeyError immediately if a new enum value is
added without a corresponding description (caught by the unit-test suite before CI).
"""

from __future__ import annotations

from typing import Any

from mintmory.core.types import ConceptLinkType, MemoryCategory, MemoryRecord, MemorySource

# ---------------------------------------------------------------------------
# Curated description maps — copied from inline comments in core/types.py
# ---------------------------------------------------------------------------

CATEGORY_DESCRIPTIONS: dict[str, str] = {
    "identity": "Persistent facts about the user/agent",
    "preference": "Stated or inferred preferences",
    "skill": "How to do something; procedures, tools, recipes",
    "context": "Current working context, active project state",
    "fact": "World-state facts, configuration values, URLs",
    "episodic": "Something that happened in a specific session",
    "temporal": "Time-bounded fact with explicit validity window",
    "relationship": "A typed link between two entities (stored as ConceptLink)",
}

LINK_TYPE_DESCRIPTIONS: dict[str, str] = {
    "relates_to": "General connection, no specific direction (symmetric)",
    "contradicts": "Cannot both be true (symmetric)",
    "refines": "B adds specificity to A; inverse: generalizes",
    "supersedes": "B replaces A completely; inverse: precedes",
    "enables": "A made B possible; inverse: enabled_by",
    "depends_on": "A requires B; inverse: supports",
    "similar_to": "A is like B (symmetric)",
    "part_of": "A is contained in B; inverse: contains",
    "uses": "A actively uses B; inverse: used_by",
    "before": "A occurred before B (temporal); inverse: after",
    "valid_until": "A is true until time T (encoded in target metadata)",
    "annotates": "A (a note) annotates B (the item it is about); inverse: annotated_by",
}

SOURCE_DESCRIPTIONS: dict[str, str] = {
    "user": "Explicitly provided by the human user",
    "agent": "Inferred or generated by the AI agent",
    "document": "Extracted from an indexed document or file",
    "inference": "Derived by the system during processing",
}


# ---------------------------------------------------------------------------
# Schema builder
# ---------------------------------------------------------------------------


def _describe(value: str, table: dict[str, str], kind: str) -> str:
    """Look up a curated description; fail with a clear message if one is missing.

    Coverage guard: adding an enum value without a description here fails loudly
    (and the unit tests trip) instead of producing a cryptic bare KeyError.
    """
    try:
        return table[value]
    except KeyError as exc:
        raise KeyError(
            f"{kind} value {value!r} has no description in mcp/_schema.py — add one."
        ) from exc


def build_schema() -> dict[str, Any]:
    """Build the mintmory://schema resource payload.

    Iterates the live enums for names and looks up the curated descriptions.
    Raises KeyError (with a clear message) if any enum value is missing a
    description (coverage guard).
    """
    categories: list[dict[str, str]] = [
        {"value": cat.value, "description": _describe(cat.value, CATEGORY_DESCRIPTIONS, "category")}
        for cat in MemoryCategory
    ]
    link_types: list[dict[str, str]] = [
        {"value": lt.value, "description": _describe(lt.value, LINK_TYPE_DESCRIPTIONS, "link_type")}
        for lt in ConceptLinkType
    ]
    sources: list[dict[str, str]] = [
        {"value": s.value, "description": _describe(s.value, SOURCE_DESCRIPTIONS, "source")}
        for s in MemorySource
    ]

    memory_record_fields: list[str] = list(MemoryRecord.model_fields)

    return {
        "categories": categories,
        "link_types": link_types,
        "sources": sources,
        "memory_record_fields": memory_record_fields,
    }
